<a href="https://colab.research.google.com/github/a-forty-two/GAIP_22_June/blob/main/r2d2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Lifecycle

# Read the input
# preprocess the input
# design multiple networks 
#### 1 design and multiple HP
#### diff designs!!!
# each design and HP combination- MODEL_N
# TRAIN, SCORE/TEST, VAL/EVAL 
# Select the best model
# EXPORT the model for deployment (Docker and Kubernetes)

In [ ]:
# IMDB - movie reviews
# TF - scrapped (web crawling/spyder) - HTML reviews 
# that are cleaned up!


In [ ]:
import tensorflow as tf
from tensorflow import keras
# Keras - Library wrapper on top of TF so that you don't have to 
#       - write TF programs! TF is just 1 of the backends!
#       - TF, NLTK, Theanos 
# keras - API inside tensorflow making our LIFE easier 
#       - prepopulated NN functions
tf.__version__

'2.8.0'

In [ ]:
dataset = keras.datasets.imdb

In [ ]:
# NO idea 
# 2 approaches
# 1) open the dataset as dictionary
# 2) open the dataset as folder/directory!
# ALL possible functions and properties offered by the class obj!


In [ ]:
dataset.__dict__
# Approach 1- dictionary

{'__builtins__': {'ArithmeticError': ArithmeticError,
  'AssertionError': AssertionError,
  'AttributeError': AttributeError,
  'BaseException': BaseException,
  'BlockingIOError': BlockingIOError,
  'BrokenPipeError': BrokenPipeError,
  'BufferError': BufferError,
  'BytesWarning': BytesWarning,
  'ChildProcessError': ChildProcessError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionError': ConnectionError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'DeprecationWarning': DeprecationWarning,
  'EOFError': EOFError,
  'Ellipsis': Ellipsis,
  'EnvironmentError': OSError,
  'Exception': Exception,
  'False': False,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'FloatingPointError': FloatingPointError,
  'FutureWarning': FutureWarning,
  'GeneratorExit': GeneratorExit,
  'IOError': OSError,
  'ImportError': ImportError,
  'ImportWarning': ImportWarning,
  'IndentationError': Ind

In [ ]:
# Approach 2
dir(dataset)
# __name__ indicates a predefined inherited function 

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'get_word_index',
 'load_data']

In [ ]:
# 2 things- get_word_index, load_data 
# functions, variables?
# dictionary tells us
# get_word_index': <function keras.datasets.imdb.get_word_index>,
# 'load_data': <function keras.datasets.imdb.load_data>}

In [ ]:
# 2 functions- load_data and get_word_index!

In [ ]:
xyz = keras.datasets
dir(xyz)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'boston_housing',
 'cifar10',
 'cifar100',
 'fashion_mnist',
 'imdb',
 'mnist',
 'reuters']

In [ ]:
word_index = dataset.get_word_index()
all_data = dataset.load_data()

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
word_index

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

In [ ]:
import inspect
inspect.getfullargspec(dataset.load_data)[0]

['path',
 'num_words',
 'skip_top',
 'maxlen',
 'seed',
 'start_char',
 'oov_char',
 'index_from']

In [ ]:
dataset = keras.datasets.imdb

In [ ]:
word_index = dataset.get_word_index()


In [ ]:
all_data = dataset.load_data(num_words=10000)
# every word beyond the 10000 -> UNKNOWN 

In [ ]:
all_data

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 194, 1153, 194, 8255, 78, 

In [ ]:
len(all_data)

2

In [ ]:
len(all_data[0])

2

In [ ]:
len(all_data[1])

2

In [ ]:
# Intutive schema - (x1,y1),(x2,y2)

In [ ]:
(x1,y1),(x2,y2) = dataset.load_data(num_words=10000)
# outside the limit of 10k -> UNKNOWN

In [ ]:
word_index["hello"]

4822

In [ ]:
len(x1), len(x2)

(25000, 25000)

In [ ]:
len(y1), len(y2)

(25000, 25000)

In [ ]:
xtrain, ytrain = x1, y1
xtest, ytest = x2, y2

In [ ]:
print(xtrain[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [ ]:
# <PAD> 0
# <START> 1
# <UNKNOWN> 2
# <UNUSED> 3
# 

In [ ]:
# index to word instead of word to index!
rev_dictionary = {val:element for element,val in word_index.items()}

In [ ]:
rev_dictionary[42]

"it's"

In [ ]:
def decoder(text):
  return " ".join( [ rev_dictionary[wrd] for wrd in text ] )

In [ ]:
decoder(xtrain[0])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but and to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other and in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of and odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit then have t

In [ ]:
decoder(xtrain[17002])

"the going field sinatra's to contrary without reality falls michael resolve and sister ways this as thanks their place this results from me will simon's violent american this of mars film of pathetic br decides agent for my and beowulf and of and and route won't comedy ralph numerous in tears of bottom camera old of bland he and to gates this of its blind too i i of you effort film is everett place this of ramones concept film is twin order romance be war to about offer new shirts filmmaker is learn deep in of create blues william stars regard mob refer results to romantic this in of everyone know of lighting strong put i i even focused movie in when involved couple film of duty br of performances whilst in long show of actually carla film whole under haunted and repeating of almost br of grayson offer i i dvd and untrue camera film of and to williams br is and grandfather in so le not immediately missions showed watched mention br cut he seen cuban and decides and there is quite in i

In [ ]:
decoder([1])
# MISTAKE- the is NOT supposed to be 1!
# 1 is reserved for <START>!

'the'

In [ ]:
print(decoder([2]))
print(decoder([3]))
# <UNKNOWN> and <UNUSED> are also missing!

and
a


In [ ]:
# print(decoder([0]))
# <PAD> doesn't even exist!

In [ ]:
dictionary_fixed = { wrd:value+3 for wrd, value in word_index.items()}

In [ ]:
dictionary_fixed["<PAD>"] = 0
dictionary_fixed["<START>"] = 1
dictionary_fixed["<UNKNOWN>"] = 2
dictionary_fixed["<UNUSED>"] = 3

In [ ]:
idx_2_word = {val:wrd for wrd, val in dictionary_fixed.items()}

In [ ]:
def decoder_fixed(text):
  return " ".join( [ idx_2_word[wrd] for wrd in text ] )

In [ ]:
decoder_fixed(xtrain[0])

"<START> this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert <UNKNOWN> is an amazing actor and now the same being director <UNKNOWN> father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for <UNKNOWN> and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also <UNKNOWN> to the two little boy's that played the <UNKNOWN> of norman and paul they were just brilliant children are often left out of the <UNKNOWN> list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and 

In [ ]:
decoder_fixed(xtrain[16388])

"<START> from the beginning this movie did have a few flaws the main character played by hayden christensen is a the rich young <UNKNOWN> who has inherited his father's considerable wealth and power and he is struggling to both fill his father's shoes and cut the <UNKNOWN> strings mother and co executive keeps too tight he also has the problem of having a heart condition and waiting in the <UNKNOWN> that is the <UNKNOWN> <UNKNOWN> <UNKNOWN> there are also minor back stories which your first instinct is to mostly ignore that become important later such as his friendship with his surgeon <UNKNOWN> howard and his romance with a middle class girl jessica alba <UNKNOWN> story lines but not bad enough to ruin the movie the only real <UNKNOWN> <UNKNOWN> moment was the name of lena <UNKNOWN> character overbearing woman named <UNKNOWN> subtle br br the <UNKNOWN> scenes are not at all <UNKNOWN> i appreciated that people who find surgery scenes scary might not the horror of being awake during <UN

In [ ]:
print(len(xtrain[0]))
print(len(xtrain[10]))
print(len(xtrain[1000]))

218
450
298


In [ ]:
# Neural Networks only accept FIXED size inputs!

In [ ]:
xtrain_padded = keras.preprocessing.sequence.pad_sequences(
    xtrain, maxlen=256, padding='post', truncating='post', value=0
)

In [ ]:
print(len(xtrain_padded[0]))
print(len(xtrain_padded[10]))
print(len(xtrain_padded[1000]))

256
256
256


In [ ]:
xtrain_padded[0]

array([   1,   14,   22,   16,   43,  530,  973, 1622, 1385,   65,  458,
       4468,   66, 3941,    4,  173,   36,  256,    5,   25,  100,   43,
        838,  112,   50,  670,    2,    9,   35,  480,  284,    5,  150,
          4,  172,  112,  167,    2,  336,  385,   39,    4,  172, 4536,
       1111,   17,  546,   38,   13,  447,    4,  192,   50,   16,    6,
        147, 2025,   19,   14,   22,    4, 1920, 4613,  469,    4,   22,
         71,   87,   12,   16,   43,  530,   38,   76,   15,   13, 1247,
          4,   22,   17,  515,   17,   12,   16,  626,   18,    2,    5,
         62,  386,   12,    8,  316,    8,  106,    5,    4, 2223, 5244,
         16,  480,   66, 3785,   33,    4,  130,   12,   16,   38,  619,
          5,   25,  124,   51,   36,  135,   48,   25, 1415,   33,    6,
         22,   12,  215,   28,   77,   52,    5,   14,  407,   16,   82,
          2,    8,    4,  107,  117, 5952,   15,  256,    4,    2,    7,
       3766,    5,  723,   36,   71,   43,  530,  4

In [ ]:
decoder_fixed(xtrain_padded[0])

"<START> this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert <UNKNOWN> is an amazing actor and now the same being director <UNKNOWN> father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for <UNKNOWN> and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also <UNKNOWN> to the two little boy's that played the <UNKNOWN> of norman and paul they were just brilliant children are often left out of the <UNKNOWN> list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and 

In [ ]:
# Embedding layer gives you a MATRIX
# i need to convert MATRIX into a number sequence!!!
# Deep Learning ONLY happens on numbers!!!

In [ ]:
# Average of the values!
# Embedding (matrix) --- average! (real number)-- pass it to the network!


In [ ]:
# Pass it to network/LEARN
# 2 fully connected layers!
# final network-> Embedding- GlobalAveragePooling- DenseX2
# TensorFlow- fully connected layers are called DENSE layers

In [ ]:
from keras.layers import Dense, Embedding, GlobalAveragePooling1D
from keras.layers import Dropout

# POOLING 
# window size

# [ 1 2 3]    ----- MAX pooling (2,2) --- [ 2  3 ]
# [ 2 0 1]                                [ 3  2 ]
# [ 3 2 1]   ------ Max pooling (1,3). --- [ 3 ]
#                                          [ 2 ]  
#                                          [ 3 ]
# --- average pooling (2,2) --- [ 5/4  3/2]
#                           --- [ 7/4  1  ]
# AveragePooling2D- blurring 

In [ ]:
# every layer has to accept whatever previous layer is throwing
# at it
# INPUT size is ONLY defined in the FIRST layer!
layer1 = Embedding(10000, 16) # vectors = 16 X 10000 = 160000
layer2 = GlobalAveragePooling1D() # This layer has NO input 
# or output definition BECAUSE it has only 1 JOB- average!
# LEARNING
layer3 = Dense(128, activation = keras.activations.relu, 
               kernel_regularizer= keras.regularizers.L1L2())
layer_drop = Dropout(0.2)
layer4 = Dense(1, activation=keras.activations.sigmoid) # one for pos, one for neg!
# Last layer should decide how many outputs we need!

In [ ]:
model = keras.models.Sequential([layer1, layer2, layer3, layer_drop,layer4])

In [ ]:
model.summary()
# weights = ?
# bias = ?
# for every output line from the network - we get a BIAS
# for every input in the network which is broken into outputs,
# we get a weight
# weights = input X output 
# bias = output
# total parameters in dense layers = input X output + output
# total parameters in embedding layer = input X output
# total parameters in GlobalAvgPooling = ?
# Embedding is EXACT calculation, hence NO BIAS

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_10 (Embedding)    (None, None, 16)          160000    
                                                                 
 global_average_pooling1d_10  (None, 16)               0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_22 (Dense)            (None, 128)               2176      
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_23 (Dense)            (None, 1)                 129       
                                                                 
Total params: 162,305
Trainable params: 162,305
Non-trainable params: 0
________________________________________________

In [ ]:
16*128 + 128

2176

In [ ]:
128*2 + 2

258

In [ ]:
# Train/Test/Evaluate

In [ ]:
layerA = Embedding(10000, 32) # vectors = 16 X 10000 = 160000
layerB = GlobalAveragePooling1D() # This layer has NO input 
# or output definition BECAUSE it has only 1 JOB- average!
# LEARNING
layerC_1 = Dense(256,activation = keras.activations.relu,
                 kernel_regularizer=keras.regularizers.L1L2())
layerC_2 = Dense(512,activation = keras.activations.relu,
                 kernel_regularizer=keras.regularizers.L1L2())

layer_drop = Dropout(0.2)

layerD = Dense(1,activation=keras.activations.sigmoid)

model2 = keras.models.Sequential([layerA, layerB, layerC_1,layerC_2, layer_drop, layerD])

In [ ]:
model2.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_11 (Embedding)    (None, None, 32)          320000    
                                                                 
 global_average_pooling1d_11  (None, 32)               0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_24 (Dense)            (None, 256)               8448      
                                                                 
 dense_25 (Dense)            (None, 512)               131584    
                                                                 
 dropout_3 (Dropout)         (None, 512)               0         
                                                                 
 dense_26 (Dense)            (None, 1)                 513       
                                                     

In [ ]:
model.compile(loss=keras.losses.binary_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])
model2.compile(loss=keras.losses.binary_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain_padded, ytrain, epochs=30)


Epoch 1/30
782/782 [==============================] - 5s 6ms/step - loss: 0.4619 - accuracy: 0.7883
Epoch 2/30
782/782 [==============================] - 4s 6ms/step - loss: 0.2541 - accuracy: 0.8999
Epoch 3/30
782/782 [==============================] - 4s 6ms/step - loss: 0.2010 - accuracy: 0.9246
Epoch 4/30
782/782 [==============================] - 4s 6ms/step - loss: 0.1682 - accuracy: 0.9384
Epoch 5/30
782/782 [==============================] - 4s 6ms/step - loss: 0.1456 - accuracy: 0.9500
Epoch 6/30
782/782 [==============================] - 4s 6ms/step - loss: 0.1246 - accuracy: 0.9585
Epoch 7/30
782/782 [==============================] - 4s 6ms/step - loss: 0.1077 - accuracy: 0.9662
Epoch 8/30
782/782 [==============================] - 4s 6ms/step - loss: 0.0941 - accuracy: 0.9719
Epoch 9/30
782/782 [==============================] - 5s 6ms/step - loss: 0.0817 - accuracy: 0.9763
Epoch 10/30
782/782 [==============================] - 5s 6ms/step - loss: 0.0718 - accuracy: 0.9796

In [ ]:
model2.fit(xtrain_padded, ytrain, epochs=30)

Epoch 1/30
782/782 [==============================] - 8s 10ms/step - loss: 0.3805 - accuracy: 0.8194
Epoch 2/30
782/782 [==============================] - 8s 10ms/step - loss: 0.2213 - accuracy: 0.9148
Epoch 3/30
782/782 [==============================] - 8s 10ms/step - loss: 0.1770 - accuracy: 0.9356
Epoch 4/30
782/782 [==============================] - 8s 10ms/step - loss: 0.1456 - accuracy: 0.9468
Epoch 5/30
782/782 [==============================] - 8s 10ms/step - loss: 0.1214 - accuracy: 0.9562
Epoch 6/30
782/782 [==============================] - 8s 10ms/step - loss: 0.0982 - accuracy: 0.9642
Epoch 7/30
782/782 [==============================] - 8s 10ms/step - loss: 0.0806 - accuracy: 0.9681
Epoch 8/30
782/782 [==============================] - 8s 10ms/step - loss: 0.0627 - accuracy: 0.9736
Epoch 9/30
782/782 [==============================] - 8s 10ms/step - loss: 0.0520 - accuracy: 0.9785
Epoch 10/30
782/782 [==============================] - 7s 10ms/step - loss: 0.0422 - accura

In [ ]:
xtest_padded = keras.preprocessing.sequence.pad_sequences(
    xtest, maxlen=256, padding='post', truncating='post', value=0
)

In [ ]:
p1 = model.predict(xtest_padded)
p2 = model2.predict(xtest_padded)

In [ ]:
print(p1[:5])
print('***')
print(p2[:5])

[[9.6285094e-06]
 [1.0000000e+00]
 [4.8648431e-05]
 [9.9853766e-01]
 [9.9999011e-01]]
***
[[6.4014275e-05]
 [1.0000000e+00]
 [9.2006373e-01]
 [9.9939346e-01]
 [1.0000000e+00]]


In [ ]:
ytest[:5]

array([0, 1, 1, 0, 1])

In [ ]:
# OUTPUT has to be scaled so that our tests can be compared!
# SIGMOID-> Logloss/Probability


In [ ]:
logic_transcoding = lambda x: 1 if x>0.5 else 0
r1 = [ logic_transcoding(result) for result in p1]
r2 = [ logic_transcoding(result) for result in p2]

In [ ]:
r1[:5]

[0, 1, 0, 1, 1]

In [ ]:
r2[:5]

[0, 1, 1, 1, 1]

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(r1, ytest)

0.81524

In [ ]:
accuracy_score(r2, ytest)

0.83628

In [ ]:
# Dealing with overfitting 

# Don't teach everything!
# 1) DROPOUT
# 
# Regularization
# 2) L1/L2/L1L2